### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by pzzyf** [vbenjs/vben3-doc#7]
<img width="1441" alt="image" src="https://github.com/vbenjs/vben3-doc/assets/56245609/5f6c80d4-65aa-47ce-b6cf-f91ffcea8eb4">

**Comment by pzzyf** [comment]
是不是mac的问题还是mac和win都有问题

**Comment by Ya2gLu** [comment]
> 是不是mac的问题还是mac和win都有问题

打包后路径有点问题，已修复🫡
